# Generated by Django 5.1.15 on 2026-09-02 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('partial', 'Partial / abandoned')], db_index=True, default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey')),
            ],
            options={
                'verbose_name': 'response',
                'verbose_name_plural': 'responses',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('spam', 'Spam'), ('low_quality', 'Low quality'), ('fraud', 'Fraud / abuse'), ('harassment', 'Harassment'), ('other', 'Other')], db_index=True, max_length=30)),
                ('note', models.TextField(verbose_name='note')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='pending', max_length=20)),
                ('resolution_note', models.TextField(blank=True, help_text='Shown to the reporter (and subject when a penalty is applied).', verbose_name='resolution note')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('penalty_kind', models.CharField(choices=[('none', 'None'), ('warning', 'Warning (progressive ladder)'), ('honor_deduction', 'Honor points deduction'), ('rank_reduction', 'Rank reduction'), ('account_freeze', 'Account freeze'), ('account_closure', 'Permanent account closure'), ('reputation', 'Reputation deduction (legacy)'), ('points', 'Survey points deduction (legacy)'), ('both', 'Reputation and points (legacy)')], db_index=True, default='none', max_length=20)),
                ('penalty_reputation', models.PositiveIntegerField(default=0, help_text='Honor/Reputation points to deduct. For warnings, the ladder amount is applied automatically (1st=-100, 2nd=-200); this field stores what was applied.', verbose_name='honor points to deduct')),
                ('penalty_points', models.PositiveIntegerField(default=0, help_text='Legacy survey Points deduction (optional).', verbose_name='survey points to deduct (legacy)')),
                ('penalty_rank_levels', models.PositiveSmallIntegerField(default=1, help_text='How many trust ranks to drop (rank reduction penalty).', verbose_name='rank levels to drop')),
                ('penalty_freeze_days', models.PositiveIntegerField(default=0, help_text='Account freeze length in days (account_freeze penalty).', verbose_name='freeze duration (days)')),
                ('penalty_executed_at', models.DateTimeField(blank=True, null=True, verbose_name='penalty executed at')),
                ('warning_number', models.PositiveSmallIntegerField(blank=True, help_text='Which warning in the ladder this was (1–5+), if kind=warning.', null=True, verbose_name='warning number applied')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='companies.company')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='surveys.survey')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='responses.response')),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(verbose_name='quality score')),
                ('tier', models.CharField(choices=[('reject', 'Reject'), ('low', 'Low'), ('standard', 'Standard'), ('high', 'High')], db_index=True, max_length=20)),
                ('components', models.JSONField(blank=True, default=dict)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('honor_granted', models.PositiveSmallIntegerField(default=0)),
                ('expected_min_seconds', models.FloatField(blank=True, null=True)),
                ('elapsed_seconds', models.FloatField(blank=True, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_assessments', to='surveys.survey')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_assessments', to=settings.AUTH_USER_MODEL)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality', to='responses.response')),
            ],
            options={
                'verbose_name': 'quality assessment',
                'verbose_name_plural': 'quality assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.JSONField(verbose_name='value')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='responses.response')),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'answers',
                'ordering': ['question__order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['survey', 'status'], name='responses_r_survey__4882d2_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['participant', 'survey'], name='responses_r_partici_5d2bbe_idx'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(condition=models.Q(('participant__isnull', False)), fields=('survey', 'participant'), name='unique_participant_per_survey'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='responses_r_status_4b205b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('response', 'question')},
        ),
    ]
