# Generated by Django 5.1.15 on 2026-09-02 00:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('user_type', models.CharField(choices=[('person', 'Person'), ('company_member', 'Company Member')], db_index=True, default='person', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'العربية')], default='en', max_length=10)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('gender', models.CharField(blank=True, choices=[('', 'Prefer not to say'), ('female', 'Female'), ('male', 'Male'), ('other', 'Other')], default='', max_length=20, verbose_name='gender')),
                ('honor_points', models.PositiveIntegerField(db_index=True, default=0, help_text='Reputation ledger (internal: honor_points). Raised by daily and weekly task completion, quality responses, and onboarding. Trust level is derived from this balance.', verbose_name='reputation')),
                ('trust_level', models.PositiveSmallIntegerField(db_index=True, default=1, help_text='1–7 derived from honor points (Newcomer … Distinguished).', verbose_name='trust level')),
                ('trust_score', models.PositiveSmallIntegerField(default=15, help_text='0–100 projection of trust level for survey targeting. Source of truth is honor_points → trust_level.', verbose_name='trust score')),
                ('warning_count', models.PositiveSmallIntegerField(default=0, help_text='Number of formal warnings received (progressive ladder).', verbose_name='warning count')),
                ('frozen_until', models.DateTimeField(blank=True, help_text='If set and in the future, the account cannot sign in.', null=True, verbose_name='frozen until')),
                ('closed_at', models.DateTimeField(blank=True, help_text='If set, the account is permanently closed.', null=True, verbose_name='permanently closed at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TrustEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_score', models.PositiveSmallIntegerField()),
                ('new_score', models.PositiveSmallIntegerField()),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(choices=[('admin_adjust', 'Admin adjustment'), ('manual', 'Manual'), ('system', 'System'), ('survey_completion', 'Survey completion (reserved)'), ('flag', 'Flag / report (reserved)')], db_index=True, default='admin_adjust', max_length=40)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trust_events_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'trust event',
                'verbose_name_plural': 'trust events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=6)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'email verification code',
                'verbose_name_plural': 'email verification codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'code', 'used_at'], name='accounts_em_user_id_170411_idx')],
            },
        ),
        migrations.CreateModel(
            name='HonorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Signed delta; negative for penalties.')),
                ('balance_after', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('registration', 'Registration'), ('email_verified', 'Email verified'), ('profile_basic', 'Basic profile completed'), ('survey_quality', 'Survey response quality'), ('daily_goal', 'Daily goal'), ('weekly_goal', 'Weekly goal'), ('achievement', 'Achievement / medal (reserved)'), ('report_penalty', 'Report penalty'), ('violation', 'Violation penalty'), ('warning', 'Warning'), ('admin_adjust', 'Admin adjustment'), ('system', 'System')], db_index=True, max_length=40)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('level_after', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='honor_events_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honor_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'honor event',
                'verbose_name_plural': 'honor events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'reason'], name='accounts_ho_user_id_6907bf_idx')],
            },
        ),
    ]
