# Generated by Django 5.1.15 on 2026-09-02 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], db_index=True, default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Private (invite / targeted only)'), ('public', 'Public (discoverable)')], default='public', max_length=20)),
                ('is_paid', models.BooleanField(db_index=True, default=False, help_text='Paid surveys may grant points. Free surveys grant XP only.', verbose_name='paid survey')),
                ('points_reward', models.PositiveIntegerField(default=0, help_text='Points given to participant on successful completion (paid surveys only).', verbose_name='points reward')),
                ('response_target', models.PositiveIntegerField(blank=True, null=True, verbose_name='response target')),
                ('allow_anonymous', models.BooleanField(default=True, verbose_name='allow anonymous')),
                ('is_frozen', models.BooleanField(db_index=True, default=False, verbose_name='is frozen')),
                ('frozen_at', models.DateTimeField(blank=True, null=True, verbose_name='frozen at')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='expires at')),
                ('targeting', models.JSONField(blank=True, default=dict, verbose_name='targeting')),
                ('category', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='category')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='tags')),
                ('company', models.ForeignKey(help_text='Owning company (including platform company SURVERA).', on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'survey',
                'verbose_name_plural': 'surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('type', models.CharField(choices=[('text', 'Text (short / long)'), ('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('yes_no', 'Yes / No'), ('rating', 'Rating (stars / numbers)'), ('scale', 'Scale (e.g. 1–10)'), ('number', 'Number'), ('date', 'Date'), ('ranking', 'Ranking'), ('matrix', 'Matrix')], default='text', max_length=30)),
                ('text', models.TextField(verbose_name='question text')),
                ('help_text', models.CharField(blank=True, max_length=500, verbose_name='help text')),
                ('is_required', models.BooleanField(default=True, verbose_name='required')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='config')),
                ('conditions', models.JSONField(blank=True, default=list, verbose_name='conditions')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ['survey', 'order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['status', 'visibility'], name='surveys_sur_status_725edc_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['company', 'status'], name='surveys_sur_company_7f64fb_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['survey', 'order'], name='surveys_que_survey__d73192_idx'),
        ),
    ]
