# Generated by Django 5.1.15 on 2026-09-02 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inapp_survey_published', models.BooleanField(default=True, verbose_name='In-app: survey published')),
                ('inapp_points_awarded', models.BooleanField(default=True, verbose_name='In-app: points awarded')),
                ('inapp_team_invite', models.BooleanField(default=True, verbose_name='In-app: team invite')),
                ('inapp_system', models.BooleanField(default=True, verbose_name='In-app: system')),
                ('email_survey_published', models.BooleanField(default=True, help_text='Only sent for private or members-only surveys.', verbose_name='Email: survey published')),
                ('email_points_awarded', models.BooleanField(default=False, help_text='Off by default — points awards can be frequent.', verbose_name='Email: points awarded')),
                ('email_team_invite', models.BooleanField(default=True, help_text='On by default — user needs to know they were added.', verbose_name='Email: team invite')),
                ('email_system', models.BooleanField(default=False, help_text='Off by default — system notices stay in-app unless opted in.', verbose_name='Email: system')),
                ('email_digest', models.CharField(choices=[('off', 'Off'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', help_text='Periodic summary of unread notifications. Invites still send immediately.', max_length=10, verbose_name='Email digest')),
                ('last_digest_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='last digest sent at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('survey_published', 'Survey published'), ('points_awarded', 'Points awarded'), ('team_invite', 'Team invite'), ('system', 'System')], db_index=True, max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, help_text='Relative URL path, e.g. /r/take/12/', max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at', '-created_at'], name='notificatio_user_id_554261_idx'), models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx')],
            },
        ),
    ]
